다차원 배열(ndarray)를 알아보겠습니다. 

# 생성 

numpy는 1차원 배열이나 2차원, 3차원 같은 다차원 배열(ndarray)을 생성할 수 있습니다. 파이썬 리스트로 다차원 배열을 생성할 수 있고, `zeros`, `empty`, `random` 같은 내장 함수를 이용할 수 도 있습니다. 다차원 배열의 자료형은 모두 같아야 합니다. 여기서는 몇 가지 방법을 이용해서 다차원 배열을 생성하도록 하겠습니다. 

In [2]:
import numpy as np

# 파이썬 리스트를 이용하여 생성 
n_arr1_1 = np.array([1, 3, 4])
n_arr1_2 = np.array([[1, 3, 4], [1, 3, 4]])
n_arr1_3 = np.array(['a', 'b', 'c'])

n_arr1_1

array([1, 3, 4])

In [3]:
# zeros: 0으로 초기화 
n_arr2 = np.zeros(4)
n_arr2

array([0., 0., 0., 0.])

In [4]:
# empty: 무작위 값으로 초기화 
n_arr3 = np.empty((2, 3, 1))
n_arr3

array([[[2.00000000e+000],
        [2.00390211e+000],
        [1.48219694e-323]],

       [[0.00000000e+000],
        [0.00000000e+000],
        [4.17201348e-309]]])

In [5]:
# random: 랜덤하게 생성 
n_arr4 = np.random.randn(2, 3)
n_arr4

array([[-0.34315753,  0.44689484, -0.97084224],
       [-0.92808689, -2.00629361, -0.67734757]])

In [6]:
# arange: 파이썬의 range와 유사 
n_arr5 = np.arange(10)
n_arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])